OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY
{
    RAM : ORIGIN = 0x80000000, LENGTH = 64K /* use bit-width of 16-bit as memory address */
}

SECTIONS
{
    .text : ALIGN(4)
    {
        *(.text._start) /* make sure that _start must be at addr. zero */
        *(.text)
        *(.text.*)
    } > RAM

    .rodata : ALIGN(4)
    {
        *(.rodata)
        *(.rodata.*)
    } > RAM

    .data : AT(ADDR(.rodata) + SIZEOF(.rodata)) ALIGN(4)
    {
        _sidata = LOADADDR(.data);
        _sdata = .;
        PROVIDE(__global_pointer$ = _sdata + 0x800);
        *(.data)
        *(.data.*)
        _edata = .;
    } > RAM

    .bss (NOLOAD) : ALIGN(4)
    {
        _sbss = .;
        *(.bss)
        *(.bss.*)
        _ebss = .;
        PROVIDE(bss_start = _sbss);
        PROVIDE(bss_end = _ebss);
    } > RAM

    .heap (NOLOAD) :
    {
        _sheap = .;
        . += 0x4000;
        _eheap = .;
        PROVIDE(heap_start = _sheap);
        PROVIDE(heap_end = _eheap);
    } > RAM

    .stack (NOLOAD) :
    {
        _estack = .;
        . += 0x4000;
        _sstack = .;
        PROVIDE(__stack_top = _sstack);
    } > RAM

    /DISCARD/ :
    {
        *(.eh_frame)
        *(.comment)
        *(.debug*)
    }
}
